name: Packer Build

on:
  workflow_dispatch:
    inputs:
      singleBuild:
        type: choice
        description: image override
        required: false
        options:
          - all
          - rhel_9_base
          - aap_demo
          - rhel_9_aap_job
          - rhel_9_aap_workflow
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main

env:
  HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
  HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
  HCP_PROJECT_ID: ${{ secrets.HCP_PROJECT_ID }}
  HCP_ORGANIZATION_ID: ${{ secrets.HCP_ORGANIZATION_ID }}
  DEFAULT_IMAGES: rhel_9_base
  CONTROLLER_VERIFY_SSL: false
  CONTROLLER_HOST: ${{ secrets.CONTROLLER_HOST }}
  CONTROLLER_USERNAME: ${{ secrets.CONTROLLER_USERNAME }}
  CONTROLLER_PASSWORD: ${{ secrets.CONTROLLER_PASSWORD }}
  CONTROLLER_PROJECT: "Packer_Project"
  ANSIBLE_OFFLINE_TOKEN: ${{ secrets.ANSIBLE_OFFLINE_TOKEN }}
  RHN_ACTIVATIONKEY: ${{ secrets.RHN_ACTIVATIONKEY }}
  RHN_ORG_ID: ${{ secrets.RHN_ORG_ID }}
  RHN_REGISTRY_SVC: ${{ secrets.RHN_REGISTRY_SVC }}
  RHN_REGISTRY_TOKEN: ${{ secrets.RHN_REGISTRY_TOKEN }}
  RHSM_OFFLINE_TOKEN: ${{ secrets.RHSM_OFFLINE_TOKEN }}
  RHSM_ALLOCATION_UUID: ${{ secrets.RHSM_ALLOCATION_UUID }}
  AAP_ADMIN_PASSWORD: ${{ vars.AAP_ADMIN_PASSWORD }}
  HUB_OFFLINE_TOKEN: ${{ secrets.ANSIBLE_OFFLINE_TOKEN }}

permissions:
  contents: read
  id-token: write

jobs:
  selectimages:
    runs-on: "ubuntu-latest"
    steps:
      - name: get-images
        id: get-images
        run: |
          if [[ "${{ inputs.singleBuild }}" != "all" ]] && [[ -n "${{ github.event.inputs.singleBuild }}" ]]; then
            export IMAGES=$(echo ${{ inputs.singleBuild }} | jq -R '["\(.)"]')
            echo "images_out"=$IMAGES""
            echo "images_out"=$IMAGES"" >> $GITHUB_OUTPUT
          else
            export IMAGES=$(echo $DEFAULT_IMAGES | jq -R 'split(", ")')
            echo "images_out"=$IMAGES""
            echo "images_out"=$IMAGES"" >> $GITHUB_OUTPUT
          fi
    outputs:
      images: ${{ steps.get-images.outputs.images_out }}
  build_images:
    runs-on: "ubuntu-latest"
    needs: [selectimages]
    strategy:
      matrix:
        image_type: ${{fromJson(needs.selectimages.outputs.images)}}
    steps:
      - uses: FraBle/clean-after-action@v1
      
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Setup Ansible
        uses: alex-oleshkevich/setup-ansible@v1.0.1
        with:
          version: 11.5.0

      - name: Print Ansible version
        run: ansible-playbook --version

      - name: Install Python dependencies
        run: pip install passlib
      
      - name: Create ansible.cfg
        run: |
          cat > ~/.ansible.cfg << EOF
          [galaxy]
          server_list = automation_hub

          [galaxy_server.automation_hub]
          url=https://console.redhat.com/api/automation-hub/
          auth_url=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
          token=${{ secrets.ANSIBLE_OFFLINE_TOKEN }}
          EOF
          chmod 600 ~/.ansible.cfg

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          role-session-name: GitHubActionsServiceRole
          role-duration-seconds: 7200
          aws-region: ${{ vars.AWS_REGION }}

      - name: Run Makefile
        shell: bash
        run: make ${{ matrix.image_type }}
        

      
